name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build main project
        run: npm run build

      - name: Build M4L project
        run: VITE_M4L_APP=true npm run build

      - name: Prepare combined deploy directory
        run: |
          mkdir deploy
          mv dist/* deploy/
          mkdir deploy/m4l
          mv dist_m4l/* deploy/m4l/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          force_orphan: true
